# This is a basic workflow to help you get started with Actions

name: Build & Test on Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: swift build -v --enable-test-discovery
      - name: Test
        run: swift test -v --enable-test-discovery
